vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO realtimechris/jsonifier
    REF "v${VERSION}"
    # Auto-generated by release CI action at realtimechris/Jsonifier
    SHA512 d514f6eff8e1405b44b9ce1fb22441c62a6fbac507e5a0b4b193e4386c9df5e6bd34b88a0a5f81647e9449345d52a0203e70ec1d6e548d85d5c179315dac25e1
	HEAD_REF main
)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
)

vcpkg_cmake_install()

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug")

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/License.md")
