name: Build-and-Test-CLANG-MacOS

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - dev
    - assembly

jobs:
  Build:
    runs-on: macos-latest
    
    strategy:
      fail-fast: false
      matrix:
        clang: [17]
        build_type: [Debug, Release]
        std: [20]

    steps:
    - uses: actions/checkout@v4

    - name: Install the latest clang compiler.
      run: |
            brew install llvm

    - name: Install Nasm.
      run: |
            brew install nasm

    - name: Configure CMake
      working-directory: ./
      run: |
           cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++ -DDEV="TRUE" -DJSONIFIER_TEST=true

    - name: Build the Test
      working-directory: ./Build
      run: |
           cmake --build . --config=${{matrix.build_type}}

    - name: Install the Test
      working-directory: ./Build
      run: |
           sudo cmake --install . --config=${{matrix.build_type}}

    - name: Run the Test
      working-directory: ./Build/Tests
      run: |
           ./Json-Performance
      continue-on-error: true
      