name: Build-and-Test-CLANG-Ubuntu-UBSan

on:
  workflow_dispatch:
  push:
    branches:
    - '*'

jobs:
  Build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v4
  
    - name: Install the latest Clang compiler.
      working-directory: Source
      run:  |
            sudo apt update && sudo apt upgrade
            wget https://apt.llvm.org/llvm.sh
            sudo chmod u+x llvm.sh
            sudo ./llvm.sh 20

    - name: Install Seaborn
      run: |
            pip install seaborn

    - name: Configure CMake
      working-directory: ./
      run: |
           sudo cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=/usr/bin/clang++-20 -DJSONIFIER_TEST=TRUE -DUBSAN=TRUE

    - name: Build the Test
      working-directory: ./Build
      run: |
           sudo cmake --build . --config=${{matrix.build_type}}

    - name: Install the Test
      working-directory: ./Build
      run: |
           sudo cmake --install . --config=${{matrix.build_type}}

    - name: Run the Test
      working-directory: ./Build/Benchmarks
      run: |
           sudo ./Json-Performance
      continue-on-error: true
      