name: Build-and-Test-GCC-Ubuntu

on:
  push:
    branches:
    - main
    - dev

jobs:
  Build:
    runs-on: ubuntu-22.04
    
    strategy:
      fail-fast: false
      matrix:
        gcc: [12]
        build_type: [Debug, Release]
        std: [20]
    env:
      CC: gcc-${{matrix.gcc}}
      CXX: g++-${{matrix.gcc}}

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      working-directory: Tests
      run: |
           cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DGITHUB_BRANCH_TYPE=${{github.ref}}

    - name: Build the Test
      working-directory: Tests/Build
      run: |
           cmake --build . --config=${{matrix.build_type}}

    - name: Run the Test
      working-directory: Tests/Build
      run: |
           ./Json-Performance
      continue-on-error: true